spring:
  application:
    name: vscouting-api-users
  cloud:
    config:
      import-check:
        enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/usersdb
    username: vscouting
    password: vscoutingpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

server:
  port: 8083

vscouting:
  security:
    jwt:
      private-key-path: /Users/luciano_v96/Desktop/workspace/vscouting-image/secrets/private_key.pem
      public-key-path: /Users/luciano_v96/Desktop/workspace/vscouting-image/secrets/public_key.pem

